### ISSUE TITLE
Add support for deref() coercions

### ISSUE THREAD

**Issue by phildawes** [racer-rust/racer#334]
#328 requires support for deref() coercions in order to be able to resolve &str methods in String

**Comment by sorccu** [comment]
Looks like #458 implemented this. This issue and many others should now be closeable.

**Comment by Thecontrarian** [comment]
This issue is still present in master at time of writing, with 84a64211a519d46479e4ebb4fd96c41dd56bd5fd the latest commit.

**Comment by sorccu** [comment]
Yes it is, unfortunately.

**Comment by Jonesey13** [comment]
This seems to a problem of finding methods on the str type itself, not by deref to &str from String. I also suspect the problem with the Vec example is due to not correctly finding methods on slices &[T], not the deref itself. For example
```
let str_ref: &str = "a str";
 let int_array = &[212, 213213];
 let int_slice: &[u32] = &int_array[0..1];
```
I cannot complete the trim method on `str_ref`` nor the len method on `int_slice`.

**Comment by TedDriggs** [comment]
@Jonesey13 string literals should work as of #728.
