### ISSUE TITLE
String literal completions

### ISSUE THREAD

**Issue by kybernetikos** [racer-rust/racer#443]
As a newcomer to rust, I benefit massively from racer helping me to discover the sorts of things I can do.

This makes me sad:

![nostringcompletions](https://cloud.githubusercontent.com/assets/430980/11731822/3e2c8b38-9f96-11e5-88d9-ad00535678fa.png)

I get completions for other things, like the vector example in the main readme, so I don't think it's just badly set up.

I'm using a cargo installed version of racer, with a nightly rust build and my rust src is set.  The screenshot is from Eclipse DT.

**Comment by phildawes** [comment]
Hi @kybernetikos. Thanks for your issue, this is in the pipeline. I'm working on getting racer to use rustc to evaluate the types of expressions, which will include literals. It's a bit hard going because the compiler isn't designed to be used in this way, but it will allow completions for any legal expression once done.

**Comment by kybernetikos** [comment]
that's good news.  thanks for all your work.

**Comment by TedDriggs** [comment]
The fix for this is now in master, and should be included in the next release.
