### ISSUE TITLE
Does not complete after newline inside `use module::{`

### ISSUE THREAD

**Issue by bluss** [racer-rust/racer#633]
I really enjoy racer nowadays, it works very well.

Here's a case for `use` imports that it does not complete correctly:

``` rust
use visit::{GraphBase, IntoNeighbors,                                            
    In                                                                           
      ^    
```

With the cursor at the ^ location, it doesn't complete from the `visit` module anymore, even though it's still inside the same `{..}` bracket from use.

**Comment by TedDriggs** [comment]
I'm able to repro this on 2.0.9. The code causing the problem appears to be [here](https://github.com/racer-rust/racer/blob/master/src/racer/core.rs#L949-L955); because the line doesn't start with `use `, racer doesn't handle it properly.

I think the fix would be to do something more like the field branch of the same `match` statement, backtracking to look for the containing statement. I'm a little concerned about making a change like that on such a frequently-hit path, but I don't see an alternative that would produce correct output.
