### ISSUE TITLE
Racer 2.0.8 finds incorrect definition match

### ISSUE THREAD

**Issue by tspiteri** [racer-rust/racer#732]
For this a.rs:
```rust
fn foo() {
    i
}
fn bar() {
    let i = 0;
    let x = 0 | i;
}
fn baz() {
    // 1 || 2;
}
```

I get the following output:
```
$ racer find-definition 2 5 a.rs
MATCH i,6,16,a.rs,FnArg,| i; } fn baz() { // 1 |
END
```
This can make racer unusable in emacs as these definitions can be very long and match very common patterns; in this example, every time a symbol starts with `i`, the definition appears when `i` is typed in.

**Comment by tspiteri** [comment]
I think this was introduced with #697. The main issues I see are:
1. It's seeing the bitwise or operator as the beginning of a closure, which goes on until the next `|` with all code, including comments, in between.
2. Even if it were a closure, it is not in scope inside `foo()`, where the definition is actually requested.

**Comment by TedDriggs** [comment]
I'm finding this error in a lot of places; it's highlighting random snippets of code when I try to find definitions. Even stranger, I've had it go to the usage of a definition, and then only when I click on that usage do I end up in the right place.

**Comment by TedDriggs** [comment]
Second update: It looks like the regex gets confused when pairs of closures are involved; it is finding everything between the closures instead of the closure definition.

**Comment by bkchr** [comment]
Yeah as I have written in the old pull request, I think I found the solution. I missed to exclude the ";", didn't thought of the bitwise operator. I can not verify it at the moment, because I'm on holidays and have no laptop with me. 

So replace:
if let Some(cap) = Regex::new(format!(r"(?:\|)(?:(?s).*,[^a-zA-Z0-9]*|[^a-zA-Z0-9]*)?(?P<definition>{})(?:[^a-zA-Z0-9\|]+[^\|]*)?(?:\|)",                                     searchstr).as_str()).unwrap().captures(scope_src)

With:
if let Some(cap) = Regex::new(format!(r"(?:\|)(?:(?s).*,[^a-zA-Z0-9]*|[^a-zA-Z0-9]*)?(?P<definition>{})(?:[^a-zA-Z0-9\|]+[^\|*;*]*)?(?:\|)",                                     searchstr).as_str()).unwrap().captures(scope_src)
