### ISSUE TITLE
Racer searches for crate sources recursively in all package dependencies

### ISSUE THREAD

**Issue by RReverser** [racer-rust/racer#831]
It seems that Racer tries to find crate source somewhat too hard, traversing not only dependencies from current Cargo.toml or Cargo.lock (which are the only accessible to current Rust code), but also dependencies of these dependencies and so on recursively. Additionally, it looks in global overrides, again, returning any match, no matter whether it's actually defined and so accessible in current crate's Cargo.toml or not.

**Comment by kngwyu** [comment]
Thanks for reporting, but, I think racer doesn't.
Could you tell me why you think so?

**Comment by RReverser** [comment]
Well I found this while trying to implement #830 and trying to figure out why I'm getting overly extensive list of crates.

Turns out, when looking for crate by name, `cargo::get_crate_file` will look at global overrides (https://github.com/racer-rust/racer/blob/cff609a5708e9244519d33649fadadb82237ec52/src/racer/cargo.rs#L696-L698) and then `Cargo.lock` without checking `Cargo.toml` whether this crate is a direct dependency at all (as both global overrides and `Cargo.lock` contain many more packages then current Rust code can actually access by name).

Then, even if it didn't find in either of those and when it does look at `Cargo.toml`, it recursively opens another `Cargo.toml` of each dependency and starts looking there - https://github.com/racer-rust/racer/blob/cff609a5708e9244519d33649fadadb82237ec52/src/racer/cargo.rs#L380-L388

**Comment by kngwyu** [comment]
Thanks, I understand.
I'm sorry I had misunderstanding that you're pointing out completion problem.

Racer searches ```Cargo.lock``` file to complete methods and so on in re-exported crates(see #812).
It's surely waste of time, but I'm not sure this should be fixed.
What the racer do here is just getting a path to crate, so source files of invisible crates won't be searched. Thus it's not critical to execution time in most of cases, I think.

For second problem(recursive search for `Cargo.toml`), hmm, it seems useless, because there's no  guarantee that source file exists if there's no `Cargo.lock` file. However, I'm not sure.

**Comment by kristate** [comment]
This seems related to #757 -- lots of recursion problems in racer.

**Comment by kngwyu** [comment]
Hmm...
OK.
I'll try to rewrite racer's file cache to check reexporting and circuit, though not now(I have 4 PRs not yet merged:fearful:).

**Comment by kristate** [comment]
@kngwyu
> I'll try to rewrite racer's file cache to check reexporting and circuit, though not now(I have 4 PRs not yet merged😨).

Thank-you!

**Comment by kngwyu** [comment]
Fixed in [my branch](https://github.com/kngwyu/racer-nightly/pull/3).

**Comment by kngwyu** [comment]
Closed via #855
