### ISSUE TITLE
Completion bug around `use ... as ...` syntax

### ISSUE THREAD

**Issue by kngwyu** [racer-rust/racer#917]
See https://github.com/racer-rust/emacs-racer/issues/105

**Comment by letmutx** [comment]
This is because when matches in use statements are returned, their matchstr is [replaced](https://github.com/racer-rust/racer/blob/98b761cce6ddc57dd51c147d8f473cb4c4d8fd55/src/racer/matchers.rs#L595) with the path alias and subsequent searches are done using the matchstr instead of the original name. To fix this we need a pass context boolean which denotes whether or not to replace the matchstr.

**Comment by kngwyu** [comment]
@letmutx 
Good catch, thanks.
